---
title: "Getting and Cleaning Data: Week 2 Quiz"
output: html_notebook
---

<br />
<br />

---------

## Question 1

Register an application with the Github API here https://github.com/settings/applications.

Access the API to get information on your instructors repositories (hint: this is the url you want "https://api.github.com/users/jtleek/repos").

Use this data to find the time that the datasharing repo was created. What time was it created?

This tutorial may be useful (https://github.com/hadley/httr/blob/master/demo/oauth2-github.r).

You may also need to run the code in the base R package and not R studio.

<br />

### Answer

<br \>
Loading packages..
```{r}
library(httr)
```

<br \>
Find OAuth settings for github: http://developer.github.com/v3/oauth/
```{r}
oauth_endpoints("github")
```

<br \>
Register an application at https://github.com/settings/applications
```{r}
myapp <- oauth_app("github",
  key = "75ffc4989df8001de43a",
  secret = "389877827ca7031f4586a37206816ec5152088dc")
```

<br \>
Get OAuth credentials
```{r}
github_token <- oauth2.0_token(oauth_endpoints("github"), myapp)
```

<br \>
Use API
```{r}
req <- GET("https://api.github.com/users/jtleek/repos", config(token = github_token))
stop_for_status(req)
output <- content(req)
```

<br \>
Find "datasharing"
 
```{r}
datashare <- which(sapply(output, FUN=function(X) "datasharing" %in% X))
datashare
```

<br \>
Find the time that the datasharing repo was created.
```{r}
list(output[[15]]$name, output[[15]]$created_at)
```

---

<br />

## Question 2

The **sqldf** package allows for execution of SQL commands on R data frames. We will use the **sqldf** package to practice the queries we might send with the **dbSendQuery()** command in **RMySQL**.

Download the American Community Survey data and load it into an R object called: *acs*
https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06pid.csv

Which of the following commands will select only the data for the probability weights pwgtp1 with ages less than 50?

<br />

### Answer

Loading packages...

```{r}
library(sqldf)
```

<br />
Downloading file...

```{r}
fileUrl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06pid.csv"
download.file(fileUrl, destfile = "acs.csv")
```

<br />
Loading data...

```{r}
acs <- read.csv("acs.csv")
head(acs)
```

<br />
Finding answer...

<br />

* Option A:
```{r}
sqldf("select * from acs")
```

<br />

* Option B:

```{r}
sqldf("select * from acs where AGEP < 50 and pwgtp1")
```

<br />

* Option C:

```{r}
sqldf("select pwgtp1 from acs")
```


<br />

* Option D:

```{r}
sqldf("select pwgtp1 from acs where AGEP < 50")
```

<br />

**Result:**

Option D: <u>sqldf("select pwgtp1 from acs where AGEP < 50")</u>

---

<br />

## Question 3

Using the same data frame you created in the previous problem, what is the equivalent function to unique(acs$AGEP)

<br />

### Answer

```{r}
Z <- unique(acs$AGEP)
```

<br />

* Option A:

```{r}
A <- sqldf("select AGEP where unique from acs")
identical(Z, A$AGEP)
```

<br />

* Option B:

```{r}
B <- sqldf("select distinct AGEP from acs")
identical(Z, B$AGEP)
```

<br />

* Option C:

```{r}
C <- sqldf("select distinct pwgtp1 from acs")
identical(Z, C$AGEP)
```

<br />

* Option D:

```{r}
D <- sqldf("select unique AGEP from acs")
identical(Z, D$AGEP)
```
 <br />
 
**Result:**

Option B: <u>sqldf("select distinct AGEP from acs")</u>

<br />

---

<br />

## Question 4

How many characters are in the 10th, 20th, 30th and 100th lines of HTML from this page:

http://biostat.jhsph.edu/~jleek/contact.html

(Hint: the nchar() function in R may be helpful)

### Answer

Fetching data...
```{r}
htmlUrl <- url("http://biostat.jhsph.edu/~jleek/contact.html")
htmlCode <- readLines(htmlUrl)
close(htmlUrl)
```

<br />
Viewing data...
```{r}
head(htmlCode)
```

<br />
Finding answer...

```{r}
c(nchar(htmlCode[10]), nchar(htmlCode[20]), nchar(htmlCode[30]), nchar(htmlCode[100]))
```

<br />

---

<br />

## Question 5

Read this data set into R and report the sum of the numbers in the fourth of the nine columns.

https://d396qusza40orc.cloudfront.net/getdata%2Fwksst8110.for

Original source of the data: http://www.cpc.ncep.noaa.gov/data/indices/wksst8110.for

(Hint: this is a fixed width file format)

<br />

### Answer

Fetching data...

```{r}
fileUrl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fwksst8110.for"
SST <- read.fwf(fileUrl, skip=4, widths=c(12, 7, 4, 9, 4, 9, 4, 9, 4))
```

<br />
Viewing file...
```{r}
head(SST)
```

<br />
Finding answer...
```{r}
sum(SST[,4])
```

<br />

---------
<center>**END**</center>
*********